// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFr3s-8-cP8EAeKKCmXZGq7PFHpOIuRgk',
    appId: '1:760526109356:web:6536956c3d583a1ff77d09',
    messagingSenderId: '760526109356',
    projectId: 'kottravel-2d580',
    authDomain: 'kottravel-2d580.firebaseapp.com',
    storageBucket: 'kottravel-2d580.firebasestorage.app',
    measurementId: 'G-CRW7QN9EDX',
    databaseURL: 'https://kottravel-2d580-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcZsAfwX-RjmsrQM0FxqEfHXe6fBT1X98',
    appId: '1:760526109356:android:770036a78fa5bd8af77d09',
    messagingSenderId: '760526109356',
    projectId: 'kottravel-2d580',
    storageBucket: 'kottravel-2d580.firebasestorage.app',
    databaseURL: 'https://kottravel-2d580-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIvEbNzAeyHXmJi2m-LqJXJkkZXFch1xw',
    appId: '1:760526109356:ios:be4e012f18ade41df77d09',
    messagingSenderId: '760526109356',
    projectId: 'kottravel-2d580',
    storageBucket: 'kottravel-2d580.firebasestorage.app',
    iosBundleId: 'com.example.kottravel',
    databaseURL: 'https://kottravel-2d580-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIvEbNzAeyHXmJi2m-LqJXJkkZXFch1xw',
    appId: '1:760526109356:ios:be4e012f18ade41df77d09',
    messagingSenderId: '760526109356',
    projectId: 'kottravel-2d580',
    storageBucket: 'kottravel-2d580.firebasestorage.app',
    iosBundleId: 'com.example.kottravel',
    databaseURL: 'https://kottravel-2d580-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFr3s-8-cP8EAeKKCmXZGq7PFHpOIuRgk',
    appId: '1:760526109356:web:be1ee25df0cb95b4f77d09',
    messagingSenderId: '760526109356',
    projectId: 'kottravel-2d580',
    authDomain: 'kottravel-2d580.firebaseapp.com',
    storageBucket: 'kottravel-2d580.firebasestorage.app',
    measurementId: 'G-3BPMR8CYC4',
    databaseURL: 'https://kottravel-2d580-default-rtdb.firebaseio.com',
  );
}
